### ISSUE TITLE
lab2指导手册的两个MMIO的地址错了

### ISSUE THREAD

**Issue by linyn-zero** [SYSU-SCC/yatcpu-docs#12]
按照代码来的话，应该是0x00000004和0x00000008，最前位不是1
![image](https://user-images.githubusercontent.com/112923198/207273214-24cf1dae-5657-40f3-9175-913be5f65420.png)

**Comment by howardlau1999** [comment]
在编程的时候我们使用 0x80000004 这个地址来操作定时器，你说的 0x4 是定时器自己收到的经过 CPU 访存模块变换后的地址

**Comment by howardlau1999** [comment]
具体可以看 `csrc/mmio.S`

**Comment by linyn-zero** [comment]
噢，谢谢
